In [14]:
!python --version

Python 3.8.8


In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.python.ops.math_ops import reduce_prod

In [2]:
print('tensorflow version : ',tf. __version__)
print('numpy version : ', np. __version__)

tensorflow version :  2.3.0
numpy version :  1.20.1


In [3]:
data=pd.read_csv('wine.csv',header=None)
df=data.sample(frac=1)
print(df.head)

<bound method NDFrame.head of      0      1     2     3     4    5     6     7     8     9     10    11  \
106   2  12.25  1.73  2.12  19.0   80  1.65  2.03  0.37  1.63  3.40  1.00   
114   2  12.08  1.39  2.50  22.5   84  2.56  2.29  0.43  1.04  2.90  0.93   
91    2  12.00  1.51  2.42  22.0   86  1.45  1.25  0.50  1.63  3.60  1.05   
66    2  13.11  1.01  1.70  15.0   78  2.98  3.18  0.26  2.28  5.30  1.12   
35    1  13.48  1.81  2.41  20.5  100  2.70  2.98  0.26  1.86  5.10  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   
103   2  11.82  1.72  1.88  19.5   86  2.50  1.64  0.37  1.42  2.06  0.94   
36    1  13.28  1.64  2.84  15.5  110  2.60  2.68  0.34  1.36  4.60  1.09   
128   2  12.37  1.63  2.30  24.5   88  2.22  2.45  0.40  1.90  2.12  0.89   
113   2  11.41  0.74  2.50  21.0   88  2.48  2.01  0.42  1.44  3.08  1.10   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04   

       12   13  
106  3.17  510  
114  3.19  

In [4]:
labels=df.iloc[:,0]
features=df.iloc[:,1:14]
X=features
y=labels

print('X: ',X)
print('y : ',y)

X:          1     2     3     4    5     6     7     8     9     10    11    12  \
106  12.25  1.73  2.12  19.0   80  1.65  2.03  0.37  1.63  3.40  1.00  3.17   
114  12.08  1.39  2.50  22.5   84  2.56  2.29  0.43  1.04  2.90  0.93  3.19   
91   12.00  1.51  2.42  22.0   86  1.45  1.25  0.50  1.63  3.60  1.05  2.65   
66   13.11  1.01  1.70  15.0   78  2.98  3.18  0.26  2.28  5.30  1.12  3.18   
35   13.48  1.81  2.41  20.5  100  2.70  2.98  0.26  1.86  5.10  1.04  3.47   
..     ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
103  11.82  1.72  1.88  19.5   86  2.50  1.64  0.37  1.42  2.06  0.94  2.44   
36   13.28  1.64  2.84  15.5  110  2.60  2.68  0.34  1.36  4.60  1.09  2.78   
128  12.37  1.63  2.30  24.5   88  2.22  2.45  0.40  1.90  2.12  0.89  2.78   
113  11.41  0.74  2.50  21.0   88  2.48  2.01  0.42  1.44  3.08  1.10  2.31   
4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

      13  
106  510  
114  385  
91   450  
66 

In [5]:
def evaluation_metrics(TP,TN,FP,FN):
    TPR=TP/(TP+FN)
    print('TPR : ',TPR)
    TNR=TN/(TN+FP)
    print('TNR : ',TNR)
    FPR=FP/(FP+TN)
    print('FPR : ',FPR)
    FNR=FN/(FN+TP)
    print('FNR : ',FNR)
    RECALL=TPR
    print('Recall : ',RECALL)
    PRECISION=TP/(TP+FP)
    print('Precision : ',PRECISION)
    F1_SCORE=(2*TP)/(2*TP+FP+FN)
    print('F1_Score : ',F1_SCORE)
    ACCURACY=(TP+TN)/(TP+FP+TN+FN)
    print('Accuracy : ',ACCURACY)
    ERROR_RATE=1-ACCURACY
    print('Error rate : ',ERROR_RATE)
    BACC=(TPR+TNR)/2
    print('BACC : ',BACC)
    TSS=TPR-FPR
    print('TSS : ',TSS)
    HSS=2*(TP*TN-FP*FN)/(((TP+FN)*(FN+TN))+((TP+FP)*(FP+TN)))
    print('HSS : ',HSS)
    sum_y=0
    for n in range(len(y_test)):
        sum_y+=(y_test[n]-y_pred[n])**2 
    BS=sum_y/len(y_test)
    print('BS : ',BS)
    
    y_meantemp=0
    for i in range(len(y_test)):
        y_meantemp+=y_test[i]
    ymean=y_meantemp/len(y_test)
    #BSS
    temp=0
    for i in range(len(y_test)):
        temp+=(y_test[i]-ymean)**2
    temp=temp/len(y_test)
    BSS=BS/temp
    print('BSS : ',BSS)
    print('\n')

In [13]:
X=np.array(X)
y=np.array(y)
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import multilabel_confusion_matrix

kf = KFold(n_splits=10)

 ####################################### Model 1 Naive Bayes #########################################
TN_TOTAL=0
TP_TOTAL=0
FP_TOTAL=0
FN_TOTAL=0

for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index] 
    model = GaussianNB()                       
    model.fit(X_train, y_train) 
    y_pred = model.predict(X_test)
    print('Evaluation metrics for each fold :\n')
    cnf_matrix = confusion_matrix(y_test, y_pred) 
    print('Confusion matrix :\n',cnf_matrix)
    [[TNs, FPs],
    [FNs, TPs]]=cnf_matrix
    print('True Negative: ',TNs)
    print('False Positive: ',FPs)
    print('False Negative: ',FNs)
    print('True Positive: ',TPs)
    evaluation_metrics(TPs,TNs,FPs,FNs)
    TN_TOTAL+=TNs
    TP_TOTAL+=TPs
    FP_TOTAL+=FPs
    FN_TOTAL+=FNs
    
TN=TN_TOTAL/10
TP=TP_TOTAL/10
FN=FN_TOTAL/10
FP=FP_TOTAL/10
print('Evaluation metrics for the average 10 fold cross validation using Naive Bayes : \n')
print('TN_AVG : ',TN)
print('TP_AVG : ',TP)
print('FN_AVG : ',FN)
print('FP_AVG : ',FP)

TPR=TP/(TP+FN)
print('TPR AVG : ',TPR)
TNR=TN/(TN+FP)
print('TNR AVG: ',TNR)
FPR=FP/(FP+TN)
print('FPR AVG: ',FPR)
FNR=FN/(FN+TP)
print('FNR AVG: ',FNR)
RECALL=TPR
print('Recall : ',RECALL)
PRECISION=TP/(TP+FP)
print('Precision : ',PRECISION)
F1_SCORE=(2*TP)/(2*TP+FP+FN)
print('F1_Score : ',F1_SCORE)
ACCURACY=(TP+TN)/(TP+FP+TN+FN)
print('Accuracy : ',ACCURACY)
ERROR_RATE=1-ACCURACY
print('Error rate : ',ERROR_RATE)
BACC=(TPR+TNR)/2
print('BACC : ',BACC)
TSS=TPR-FPR
print('TSS : ',TSS)
HSS=2*(TP*TN-FP*FN)/(((TP+FN)*(FN+TN))+((TP+FP)*(FP+TN)))
print('HSS : ',HSS)
sum_y=0
for n in range(len(y_test)):
    sum_y+=(y_test[n]-y_pred[n])**2 
BS=sum_y/len(y_test)
print('BS : ',BS)
    
y_meantemp=0
for i in range(len(y_test)):
    y_meantemp+=y_test[i]
ymean=y_meantemp/len(y_test)
temp=0
for i in range(len(y_test)):
    temp+=(y_test[i]-ymean)**2
temp=temp/len(y_test)
BSS=BS/temp
print('BSS : ',BSS)
print('\n')

df1=pd.DataFrame({"TP": TP,
                "FP": FP,
                "FN": FN,
                "TN": TN,
                "TPR":TPR,
                "FPR":FPR,
                "TNR":TNR,
                "FNR":FNR,
                "RECALL":RECALL,
                'PRECISION':PRECISION,
                'F1_SCORE':F1_SCORE,
                'Accuracy':ACCURACY,
                'Error rate':ERROR_RATE,
                'BACC':BACC,
                'TSS':TSS,
                'HSS':HSS,
                'BS' :BS,
                'BSS':BSS
                 },
                 index=["Naive Bayes"])


Evaluation metrics for each fold :

Confusion matrix :
 [[5 0]
 [0 8]]
True Negative:  5
False Positive:  0
False Negative:  0
True Positive:  8
TPR :  1.0
TNR :  1.0
FPR :  0.0
FNR :  0.0
Recall :  1.0
Precision :  1.0
F1_Score :  1.0
Accuracy :  1.0
Error rate :  0.0
BACC :  1.0
TSS :  1.0
HSS :  1.0
BS :  0.0
BSS :  0.0


Evaluation metrics for each fold :

Confusion matrix :
 [[3 1]
 [0 9]]
True Negative:  3
False Positive:  1
False Negative:  0
True Positive:  9
TPR :  1.0
TNR :  0.75
FPR :  0.25
FNR :  0.0
Recall :  1.0
Precision :  0.9
F1_Score :  0.9473684210526315
Accuracy :  0.9230769230769231
Error rate :  0.07692307692307687
BACC :  0.875
TSS :  0.75
HSS :  0.8059701492537313
BS :  0.07692307692307693
BSS :  0.3611111111111111


Evaluation metrics for each fold :

Confusion matrix :
 [[4 0]
 [0 9]]
True Negative:  4
False Positive:  0
False Negative:  0
True Positive:  9
TPR :  1.0
TNR :  1.0
FPR :  0.0
FNR :  0.0
Recall :  1.0
Precision :  1.0
F1_Score :  1.0
Accuracy :  1

In [14]:
df1

TP   FP   FN   TN  TPR       FPR       TNR  FNR  RECALL  \
Naive Bayes  7.1  0.2  0.0  5.7  1.0  0.033898  0.966102  0.0     1.0   

             PRECISION  F1_SCORE  Accuracy  Error rate      BACC       TSS  \
Naive Bayes   0.972603  0.986111  0.984615    0.015385  0.983051  0.966102   

                  HSS        BS       BSS  
Naive Bayes  0.968877  0.076923  0.309524

In [15]:
#################### MOdel 2 Random Forest ######################################
##print('The model is')
TN_TOTAL=0
TP_TOTAL=0
FP_TOTAL=0
FN_TOTAL=0

for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index] 
    rf= RandomForestClassifier(n_estimators=20, random_state=0)
    rf.fit(X_train, y_train)
    y_predrf=rf.predict(X_test)
    print('Evaluation metrics achieved by Random Forest in each fold : ')
    cnf_matrix = confusion_matrix(y_test, y_predrf)
    print('Confusion matrix :\n',cnf_matrix)
    [[TNs, FPs],
    [FNs, TPs]]=cnf_matrix
    print('True Negative: ',TNs)
    print('False Positive: ',FPs)
    print('False Negative: ',FNs)
    print('True Positive: ',TPs)
    evaluation_metrics(TPs,TNs,FPs,FNs)
    TN_TOTAL+=TNs
    TP_TOTAL+=TPs
    FP_TOTAL+=FPs
    FN_TOTAL+=FNs
    
TN=TN_TOTAL/10
TP=TP_TOTAL/10
FN=FN_TOTAL/10
FP=FP_TOTAL/10
print('Evaluation metrics for the average 10 fold cross validation using Random Forest : \n')
print('TN_AVG : ',TN)
print('TP_AVG : ',TP)
print('FN_AVG : ',FN)
print('FP_AVG : ',FP)

TPR=TP/(TP+FN)
print('TPR AVG : ',TPR)
TNR=TN/(TN+FP)
print('TNR AVG: ',TNR)
FPR=FP/(FP+TN)
print('FPR AVG: ',FPR)
FNR=FN/(FN+TP)
print('FNR AVG: ',FNR)
RECALL=TPR
print('Recall : ',RECALL)
PRECISION=TP/(TP+FP)
print('Precision : ',PRECISION)
F1_SCORE=(2*TP)/(2*TP+FP+FN)
print('F1_Score : ',F1_SCORE)
ACCURACY=(TP+TN)/(TP+FP+TN+FN)
print('Accuracy : ',ACCURACY)
ERROR_RATE=1-ACCURACY
print('Error rate : ',ERROR_RATE)
BACC=(TPR+TNR)/2
print('BACC : ',BACC)
TSS=TPR-FPR
print('TSS : ',TSS)
HSS=2*(TP*TN-FP*FN)/(((TP+FN)*(FN+TN))+((TP+FP)*(FP+TN)))
print('HSS : ',HSS)
sum_y=0
for n in range(len(y_test)):
    sum_y+=(y_test[n]-y_pred[n])**2 
BS=sum_y/len(y_test)
print('BS : ',BS)
    
y_meantemp=0
for i in range(len(y_test)):
    y_meantemp+=y_test[i]
ymean=y_meantemp/len(y_test)
temp=0
for i in range(len(y_test)):
    temp+=(y_test[i]-ymean)**2
temp=temp/len(y_test)
BSS=BS/temp
print('BSS : ',BSS)
print('\n')

df2=pd.DataFrame({"TP": TP,
                "FP": FP,
                "FN": FN,
                "TN": TN,
                "TPR":TPR,
                "FPR":FPR,
                "TNR":TNR,
                "FNR":FNR,
                "RECALL":RECALL,
                'PRECISION':PRECISION,
                'F1_SCORE':F1_SCORE,
                'Accuracy':ACCURACY,
                'Error rate':ERROR_RATE,
                'BACC':BACC,
                'TSS':TSS,
                'HSS':HSS,
                'BS' :BS,
                'BSS':BSS
                 },
                 index=["Random Forest"])


Evaluation metrics achieved by Random Forest in each fold : 
Confusion matrix :
 [[5 0]
 [0 8]]
True Negative:  5
False Positive:  0
False Negative:  0
True Positive:  8
TPR :  1.0
TNR :  1.0
FPR :  0.0
FNR :  0.0
Recall :  1.0
Precision :  1.0
F1_Score :  1.0
Accuracy :  1.0
Error rate :  0.0
BACC :  1.0
TSS :  1.0
HSS :  1.0
BS :  0.46153846153846156
BSS :  1.9499999999999997


Evaluation metrics achieved by Random Forest in each fold : 
Confusion matrix :
 [[4 0]
 [1 8]]
True Negative:  4
False Positive:  0
False Negative:  1
True Positive:  8
TPR :  0.8888888888888888
TNR :  1.0
FPR :  0.0
FNR :  0.1111111111111111
Recall :  0.8888888888888888
Precision :  1.0
F1_Score :  0.9411764705882353
Accuracy :  0.9230769230769231
Error rate :  0.07692307692307687
BACC :  0.9444444444444444
TSS :  0.8888888888888888
HSS :  0.8311688311688312
BS :  0.6923076923076923
BSS :  3.25


Evaluation metrics achieved by Random Forest in each fold : 
Confusion matrix :
 [[4 0]
 [0 9]]
True Negative:  4

In [16]:
df2

TP   FP   FN   TN       TPR  FPR  TNR       FNR    RECALL  \
Random Forest  7.0  0.0  0.1  5.9  0.985915  0.0  1.0  0.014085  0.985915   

               PRECISION  F1_SCORE  Accuracy  Error rate      BACC       TSS  \
Random Forest        1.0  0.992908  0.992308    0.007692  0.992958  0.985915   

                    HSS        BS       BSS  
Random Forest  0.984505  0.076923  0.309524

In [17]:
import warnings
warnings.filterwarnings("ignore")
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

try:
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
except Exception as e:
    print('')

In [18]:
###################################### Model 3 LSTM (Deep Learning) #########################################
TN_TOTAL=0
TP_TOTAL=0
FP_TOTAL=0
FN_TOTAL=0
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    #reshape the data to match 3 dimension for LSTM layers.
    X_train = X_train.reshape(X_train.shape[0], X_train.shape[1],1)
    X_test = X_test.reshape(X_test.shape[0], X_test.shape[1],1)
    
#     print('X_train.shape:', X_train.shape)
#     print('y_train.shape:', y_train.shape)
#     print('X_test.shape:', X_test.shape)
#     print('y_test.shape:', y_test.shape)

    lstm_model = tf.keras.Sequential()
    lstm_model.add(tf.keras.layers.LSTM(64,return_sequences=True, return_state=False,input_shape=(X_test.shape[1],X_test.shape[2]))) # Instruction: in case you change the data format
    lstm_model.add(tf.keras.layers.LSTM(64, return_sequences=True, return_state=False))
    lstm_model.add(tf.keras.layers.LSTM(64, return_sequences=True, return_state=False))
    lstm_model.add(tf.keras.layers.LSTM(64, return_sequences=True, return_state=False))
    lstm_model.add(tf.keras.layers.LSTM(64, return_sequences=True, return_state=False))
    #when we return the sequence, we change the shape, so last layer should not return sequnce to the Dense layer
    lstm_model.add(tf.keras.layers.Flatten())
    lstm_model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

    # Compile the Model
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
    lstm_model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])
    #lstm_model.summary()
    lstm_model.fit(X_train, y_train,epochs=100,batch_size=1, verbose = 0)
    #more epochs the better and we can add EarlyStopping in callbacks so that if the accuracy is not improving, it will stop.
    y_pred = lstm_model.predict(X_test)
    #print(y_pred)
    score = lstm_model.evaluate(X_test, y_test,verbose=0)
    print('Evaluation metrics for lstm model is : \n',score)
    cnf_matrix = confusion_matrix(y_test, y_pred)
    print('Confusion matrix :\n',cnf_matrix)
    [[TNs, FPs],
    [FNs, TPs]]=cnf_matrix
    print('True Negative: ',TNs)
    print('False Positive: ',FPs)
    print('False Negative: ',FNs)
    print('True Positive: ',TPs)
    evaluation_metrics(TPs,TNs,FPs,FNs)
    TN_TOTAL+=TNs
    TP_TOTAL+=TPs
    FP_TOTAL+=FPs
    FN_TOTAL+=FNs
    
TN=TN_TOTAL/10
TP=TP_TOTAL/10
FN=FN_TOTAL/10
FP=FP_TOTAL/10
print('Evaluation metrics for the average 10 fold cross validation using LSTM : \n')
print('TN_AVG : ',TN)
print('TP_AVG : ',TP)
print('FN_AVG : ',FN)
print('FP_AVG : ',FP)

TPR=TP/(TP+FN)
print('TPR AVG : ',TPR)
TNR=TN/(TN+FP)
print('TNR AVG: ',TNR)
FPR=FP/(FP+TN)
print('FPR AVG: ',FPR)
FNR=FN/(FN+TP)
print('FNR AVG: ',FNR)
RECALL=TPR
print('Recall : ',RECALL)
PRECISION=TP/(TP+FP)
print('Precision : ',PRECISION)
F1_SCORE=(2*TP)/(2*TP+FP+FN)
print('F1_Score : ',F1_SCORE)
ACCURACY=(TP+TN)/(TP+FP+TN+FN)
print('Accuracy : ',ACCURACY)
ERROR_RATE=1-ACCURACY
print('Error rate : ',ERROR_RATE)
BACC=(TPR+TNR)/2
print('BACC : ',BACC)
TSS=TPR-FPR
print('TSS : ',TSS)
HSS=2*(TP*TN-FP*FN)/(((TP+FN)*(FN+TN))+((TP+FP)*(FP+TN)))
print('HSS : ',HSS)
sum_y=0
for n in range(len(y_test)):
    sum_y+=(y_test[n]-y_pred[n])**2 
BS=sum_y/len(y_test)
print('BS : ',BS)
    
y_meantemp=0
for i in range(len(y_test)):
    y_meantemp+=y_test[i]
ymean=y_meantemp/len(y_test)
temp=0
for i in range(len(y_test)):
    temp+=(y_test[i]-ymean)**2
temp=temp/len(y_test)
BSS=BS/temp
print('BSS : ',BSS)
print('\n')

df3=pd.DataFrame({"TP": TP,
                "FP": FP,
                "FN": FN,
                "TN": TN,
                "TPR":TPR,
                "FPR":FPR,
                "TNR":TNR,
                "FNR":FNR,
                "RECALL":RECALL,
                'PRECISION':PRECISION,
                'F1_SCORE':F1_SCORE,
                'Accuracy':ACCURACY,
                'Error rate':ERROR_RATE,
                'BACC':BACC,
                'TSS':TSS,
                'HSS':HSS,
                'BS' :BS,
                'BSS':BSS
                 },
                 index=["LSTM"])


Evaluation metrics for lstm model is : 
 [-4326.6728515625, 0.38461539149284363]
Confusion matrix :
 [[5 0]
 [8 0]]
True Negative:  5
False Positive:  0
False Negative:  8
True Positive:  0
TPR :  0.0
TNR :  1.0
FPR :  0.0
FNR :  1.0
Recall :  0.0
Precision :  nan
F1_Score :  0.0
Accuracy :  0.38461538461538464
Error rate :  0.6153846153846154
BACC :  0.5
TSS :  0.0
HSS :  0.0
BS :  [0.61538464]
BSS :  [2.6000001]


Evaluation metrics for lstm model is : 
 [-4832.19091796875, 0.3076923191547394]
Confusion matrix :
 [[4 0]
 [9 0]]
True Negative:  4
False Positive:  0
False Negative:  9
True Positive:  0
TPR :  0.0
TNR :  1.0
FPR :  0.0
FNR :  1.0
Recall :  0.0
Precision :  nan
F1_Score :  0.0
Accuracy :  0.3076923076923077
Error rate :  0.6923076923076923
BACC :  0.5
TSS :  0.0
HSS :  0.0
BS :  [0.6923077]
BSS :  [3.2500002]


Evaluation metrics for lstm model is : 
 [-4835.5498046875, 0.3076923191547394]
Confusion matrix :
 [[4 0]
 [9 0]]
True Negative:  4
False Positive:  0
False Nega

In [19]:
df3

TP   FP   FN   TN  TPR  FPR  TNR  FNR  RECALL  PRECISION  F1_SCORE  \
LSTM  0.0  0.0  7.1  5.9  0.0  0.0  1.0  1.0     0.0        NaN       0.0   

      Accuracy  Error rate  BACC  TSS  HSS        BS       BSS  
LSTM  0.453846    0.546154   0.5  0.0  0.0  0.538462  2.166667

In [20]:
# Creating Table to have all the evaluation metrics in one place.
frames=[df1,df2,df3]
result=pd.concat(frames)

In [21]:
result

TP   FP   FN   TN       TPR       FPR       TNR       FNR  \
Naive Bayes    7.1  0.2  0.0  5.7  1.000000  0.033898  0.966102  0.000000   
Random Forest  7.0  0.0  0.1  5.9  0.985915  0.000000  1.000000  0.014085   
LSTM           0.0  0.0  7.1  5.9  0.000000  0.000000  1.000000  1.000000   

                 RECALL  PRECISION  F1_SCORE  Accuracy  Error rate      BACC  \
Naive Bayes    1.000000   0.972603  0.986111  0.984615    0.015385  0.983051   
Random Forest  0.985915   1.000000  0.992908  0.992308    0.007692  0.992958   
LSTM           0.000000        NaN  0.000000  0.453846    0.546154  0.500000   

                    TSS       HSS        BS       BSS  
Naive Bayes    0.966102  0.968877  0.076923  0.309524  
Random Forest  0.985915  0.984505  0.076923  0.309524  
LSTM           0.000000  0.000000  0.538462  2.166667

In [22]:
result_transpose=result.T
print(result_transpose)

            Naive Bayes  Random Forest      LSTM
TP             7.100000       7.000000  0.000000
FP             0.200000       0.000000  0.000000
FN             0.000000       0.100000  7.100000
TN             5.700000       5.900000  5.900000
TPR            1.000000       0.985915  0.000000
FPR            0.033898       0.000000  0.000000
TNR            0.966102       1.000000  1.000000
FNR            0.000000       0.014085  1.000000
RECALL         1.000000       0.985915  0.000000
PRECISION      0.972603       1.000000       NaN
F1_SCORE       0.986111       0.992908  0.000000
Accuracy       0.984615       0.992308  0.453846
Error rate     0.015385       0.007692  0.546154
BACC           0.983051       0.992958  0.500000
TSS            0.966102       0.985915  0.000000
HSS            0.968877       0.984505  0.000000
BS             0.076923       0.076923  0.538462
BSS            0.309524       0.309524  2.166667
